spring:
  application:
    name: notificacao

  cloud:
    openfeign:
      okhttp:
        enabled: true

  mail:
    nomeRemetente: Arthur
    host: smtp.gmail.com
    port: 587
    username: arthurrodrigues1801r@gmail.com
    password: vsrs ubsn mswl foxo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  client:
    url:
      citacao: https://api.api-ninjas.com
    key:
      citacao: 7XH1W7DPtVYnFSX8YILnP6QHadBimWJEw21oS6eM

  thymeleaf:
    enable: true

server:
  port: 8082