spring:
  application:
    name: notificacao
  cloud:
    openfeign:
      okhttp:
        enabled: true
  mail:
    nomeRemetente: ${NOME_REMETENTE_EMAIL_NOTIFICACAO}
    host: ${HOST_EMAIL_NOTIFICACAO}
    port: ${PORTA_EMAIL_NOTIFICACAO}
    username: ${USERNAME_EMAIL_NOTIFICACAO}
    password: ${PASSWORD_EMAIL_NOTIFICACAO}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  client:
    url:
      citacao: ${URL_API_CITACAO}
    key:
      citacao: ${KEY_API_CITACAO}
  thymeleaf:
    enable: true
server:
  port: ${PORTA_NOTIFICACAO}