spring.application.name=notificacao
server.port=8082
usuario.url=http://localhost:8080
tarefa.url=http://localhost:8081
password.contaservico=notificacao875691$tarefas%&NT
email.contaservico=notificacao@gmail.com